name: Build project
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
#  build:
#    name: Build
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
      # TODO Build projects
      # TODO deploy
      # - name: Run API Tests
      #  id: run-newman
      #  uses: anthonyvscode/newman-action@v1
      #  with:
      #    collection: postman/postman-collection.json
      #    environment: postman/postman-heroku-environment.json
      #    delayRequest: 50
      #    reporters: cli
    deploy_booking_and_office:
      name: DeployBookingAndOffice
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: DeployOffice
          uses: akhileshns/heroku-deploy@v3.4.6
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "curse-office"
            heroku_email: "evgenij997@yandex.ru"
            appdir: "office"
          env:
            HD_MINIMAL_MODE: 1

        - name: DeployBooking
          uses: akhileshns/heroku-deploy@v3.4.6
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "curse-booking"
            heroku_email: "evgenij997@yandex.ru"
            appdir: "booking"
          env:
            HD_OFFICE_SERVICE_URL: "curse-office.herokuapp.com"
            HD_MINIMAL_MODE: 1


    deploy_session_and_gateway:
      name: DeploySessionAndGateway
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: DeployGateway
          uses: akhileshns/heroku-deploy@v3.4.6
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "curse-gateway"
            heroku_email: "evgenij997@yandex.ru"
            appdir: "gateway"
          env:
            HD_OFFICE_SERVICE_URL: "curse-office.herokuapp.com"
            HD_BOOKING_SERVICE_URL: "curse-booking.herokuapp.com"
            HD_FRONT_URL: "curse-front.herokuapp.com"

        - name: DeploySession
          uses: akhileshns/heroku-deploy@v3.4.6
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "curse-session"
            heroku_email: "evgenij997@yandex.ru"
            appdir: "session"
          env:
            HD_MINIMAL_MODE: 1
            HD_FRONT_URL: "curse-front.herokuapp.com"


    deploy_front:
      name: DeployFront
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: DeployFront
          uses: akhileshns/heroku-deploy@v3.4.6
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "curse-front"
            heroku_email: "evgenij997@yandex.ru"
            appdir: "front"
          env:
            HD_SESSION_URL: "curse-session.herokuapp.com"
            HD_GATEWAY_URL: "curse-gateway.herokuapp.com"
