name: Build project
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
#  build:
#    name: Build
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
      # TODO Build projects
      # TODO deploy
      # - name: Run API Tests
      #  id: run-newman
      #  uses: anthonyvscode/newman-action@v1
      #  with:
      #    collection: postman/postman-collection.json
      #    environment: postman/postman-heroku-environment.json
      #    delayRequest: 50
      #    reporters: cli
    deploy_front:
      name: DeployFront
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@v3.4.6 # This is the action
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "curse-front"
            heroku_email: "evgenij997@yandex.ru"
            appdir: "front"

        - name: Sleep for 10s
          uses: juliangruber/sleep-action@v1
          with:
            time: 10s


    deploy_gateway:
      name: DeployGateway
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@v3.4.6 # This is the action
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "curse-gateway"
            heroku_email: "evgenij997@yandex.ru"
            appdir: "gateway"

        - name: Sleep for 10s
          uses: juliangruber/sleep-action@v1
          with:
            time: 10s


    deploy_session:
      name: DeploySession
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@v3.4.6 # This is the action
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "curse-session"
            heroku_email: "evgenij997@yandex.ru"
            appdir: "session"
          env:
            HD_MINIMAL_MODE: 1

        - name: Sleep for 10s
          uses: juliangruber/sleep-action@v1
          with:
            time: 10s


    deploy_office:
      name: DeployOffice
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@v3.4.6 # This is the action
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "curse-office"
            heroku_email: "evgenij997@yandex.ru"
            appdir: "office"
          env:
            HD_MINIMAL_MODE: 1

        - name: Sleep for 10s
          uses: juliangruber/sleep-action@v1
          with:
            time: 10s
