name: Build project
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
    deploy_all:
      name: DeployBookingAndOffice
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: DeployOffice
          uses: akhileshns/heroku-deploy@v3.4.6
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "curse-office"
            heroku_email: "evgenij997@yandex.ru"
            appdir: "office"
          env:
            HD_MINIMAL_MODE: 1

        - name: DeployBooking
          uses: akhileshns/heroku-deploy@v3.4.6
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "curse-booking"
            heroku_email: "evgenij997@yandex.ru"
            appdir: "booking"
          env:
            HD_OFFICE_SERVICE_URL: "curse-office.herokuapp.com"
            HD_MINIMAL_MODE: 1

        - name: DeployGateway
          uses: akhileshns/heroku-deploy@v3.4.6
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "curse-gateway"
            heroku_email: "evgenij997@yandex.ru"
            appdir: "gateway"
          env:
            HD_OFFICE_SERVICE_URL: "curse-office.herokuapp.com"
            HD_BOOKING_SERVICE_URL: "curse-booking.herokuapp.com"
            HD_FRONT_URL: "curse-front.herokuapp.com"

        - name: DeploySession
          uses: akhileshns/heroku-deploy@v3.4.6
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "curse-session"
            heroku_email: "evgenij997@yandex.ru"
            appdir: "session"
          env:
            HD_MINIMAL_MODE: 1
            HD_FRONT_URL: "curse-front.herokuapp.com"

        - name: DeployFront
          uses: akhileshns/heroku-deploy@v3.4.6
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "curse-front"
            heroku_email: "evgenij997@yandex.ru"
            appdir: "front"
          env:
            HD_SESSION_URL: "curse-session.herokuapp.com"
            HD_GATEWAY_URL: "curse-gateway.herokuapp.com"
